[package]
name = "ve"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
rand_distr = "0.4"
nalgebra = "0.25.3"
sha2 = "0.11.0-rc.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22.1"
num-bigint = "0.4.6"
